//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_details
    {
        public string transaction_id { get; set; }
        public string guitar_id { get; set; }
        public int quantity { get; set; }
    
        public virtual guitar guitar { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
