//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokoBuku.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public string TransactionDetailID { get; set; }
        public string TransactionID { get; set; }
        public string BookID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
