//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoLWebVersion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Detail
    {
        public string TransactionID { get; set; }
        public string BookID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
